### PR TITLE
Connect repo with icare extraction client

### PR DESCRIPTION
**Pull request by mgramigna**
* Rename repo
* Update main field of package.json to expose client
* Add proper uuid module (was giving us a deprecation warning)

### CODE REVIEW

**Review by kjmahalingam — DISMISSED** [review]
Nice work! All looks good to me.

**Comment by Dtphelan1** [comment]
This looks good to me.

**Review by Dtphelan1 — APPROVED** [review]

**Review by Dtphelan1 — CHANGES_REQUESTED** [review]
errr standby

**Comment by Dtphelan1** [comment]
DP1 - Update the readme with new run instructions. `node . `no longer runs the `index.js` file since we've changed main in our `package.json` file. While changing the main helps in the export of our tool and importing it into other projects, it makes running the local CLI more verbose. I'm fine with that tradeoff, we just need to update our docs appropriately.

**Comment by Dtphelan1** [comment]
After DP1 though I'm good to approve 👍

**Comment by mgramigna** [comment]
pushed

**Comment by Dtphelan1** [comment]
LGTM.

**Review by Dtphelan1 — APPROVED** [review]

**Comment by Dtphelan1** [comment]
Needs another lookover by D Mahal since changes were made since previous approval

**Review by kjmahalingam — APPROVED** [review]
Yup, all changes look good to me!

**Pull request merged**
