### PR TITLE
Update README to reflect current state of implementation

### PR DESCRIPTION
**Pull request by kjmahalingam**
Update README to reflect current state of implementation

### CODE REVIEW

**Comment by Dtphelan1** [comment]
This all looks good to me - hard to fully test that things are working since I don't want to push anything to the AWS servers! Is there any suggestions you have for making sure that I can run code properly without firing off actual FHIR messages? Or would it be alright to just do that?

**Comment by kjmahalingam** [comment]
Thanks for the review, @Dtphelan1 ! 

I would not say that there is a really good way (other than the unit tests) to verify that it is functional, other than sending up the actual FHIR, unfortunately. Typically when we were working on this as a much smaller team, we didn't have these issues. Now, we have to be somewhat more cognizant of that.

I would still say that it is fine to just go ahead and fire off the actual messages, if you want to verify functionality. Any message that can successfully be posted and put into the database will have been a valid one anyway, so it won't mess with the process flow much.

For now, @danlee1025 , just be aware that there might be more message bundles posted up to the database, since I'm aware you're working on the extraction side of things. That shouldn't affect things other than operating on more than one bundle, rather than the single one up there right now.

**Comment by Dtphelan1** [comment]
One thing, DP1: Could we add a section on testing? This mirrors the README in the other repo. 
Barring that comment, this looks good to me

**Comment by Dtphelan1** [comment]
Alright DP2 that's totally unrealated to this task, but while we have a PR up..... could/should we add `config.json` at the root level to our `.gitignore`?

**Comment by kjmahalingam** [comment]
DP1 and DP2 have been addressed in the latest commit. You also made me realize that the associated icaredata-platform PR had a typo, and I am fixing that one accordingly.

**Comment by Dtphelan1** [comment]
Lol :)

**Review by jafeltra — APPROVED** [review]
Looks good to me!

**Review by Dtphelan1 — APPROVED** [review]

**Pull request merged**
